apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
  namespace: app-namespace
  annotations:
    # Use nginx ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Force HTTPS even without proper certificate (for self-signed certs) - useful for development
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  ingressClassName: nginx # Specify the ingress class to use the nginx controller (default).
  tls:
  - hosts:
    - mongo.local
    secretName: mongo-tls-secret

  rules:
  - host: mongo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongodb-express-service
            port:
              number: 8081
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mongodb-express-service
            port:
              number: 8081