# Secret and ConfigMap for database-namespace (used by MongoDB)
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: database-namespace
type: Opaque
data:
  # base64 encoded: username
  mongo-root-username: dXNlcm5hbWU=
  # base64 encoded: password
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: database-namespace
data:
  # Full service URL with namespace for cross-namespace communication
  database_url: mongodb-service.database-namespace.svc.cluster.local
# Secret and ConfigMap for app-namespace (used by Mongo-Express)
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: app-namespace
type: Opaque
data:
  # base64 encoded: username
  mongo-root-username: dXNlcm5hbWU=
  # base64 encoded: password
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: app-namespace
data:
  # Full service URL for cross-namespace communication
  database_url: mongodb-service.database-namespace.svc.cluster.local

---
# TLS Secret for Ingress
apiVersion: v1
kind: Secret
metadata:
  name: mongo-tls-secret
  namespace: app-namespace
type: kubernetes.io/tls
data:
  # base64 encoded certificate (replace with your own for production)
  tls.crt: pJaHZjTkFRRUxCUUFEZ2dFQgpBRzg4RVpnN2ZVcVZjYXVGRUVZczJGY3FCY244TEdKbldjbmZncTJNTy9PNVdMRHIzbjR1S1hBOWtYcmI3K1gvCkJteDJtUElZc000NVdDL2ZaTHZaUnJQcUhiL29HZHM4VEM5NTRoUGlza1VRWGpTRGQ4bkdlRldKeFg5bGM0eTcKM1lyTHFXMDR0RCtxZm8zZncrK3dCSTVBRTZvTnlkd016cWY5a2g0TTRoTUY1am9oUTFvVmFuT3h1UlNmdUtxTAoySnk2Q3dUalRGSXgzKzNVeDFxdWdEckV3NnJFbEwxaEQ2bVdmeXdWOGU3a1h6eWZ6bVNQeWUzSWt2ZUhIOGNoCmhML2lTZEx3cnVHbjhMaFB3YVFCR3RGZTQyem1QbndZSUt4YzkwMGRtcWNwZFFYTzZzQUhFcG01KzRVc1duMzgKSmR5aTJ6ZzBEUjlDZ280TlVXSTlhSE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  # base64 encoded key (replace with your own for production)
  tls.key: lJIbE1lNU41VHZpbkR6b3crYk5Na1crTG5Bb0dBUlNSYwpKTFJBSHozN3g5eVQwa24rekgrTWliY3JGNEp6THlDVkhSMzNvaithVkROQktkWWR6TythNkY3OHVRVDBCd0c5CmdtMXZ0RFFkN29ObTdaUVJZNWlUQm5xaWcyM0FTZkQ2SzZoeTZBOWpmRzJRUWJvRk0vNnpaeDlxZ09VQVl6WTYKMzU5eTFaUzlwR0g3QlV4aGVFUHZaODJKaHhrd09rUFRDYkg2OGlzQ2dZRUE1NzRkSFBsWUt0dkVvbFVRMnp5Lwo1SFJPd3BQSzRmNWhmKzZyRTNqY00xcE1pOXNwam1Neko3RDkxRWlWODlaVEZQZkVNZEN4Q2d6U0JaV25zeEliCnpjNjlHZnFrOXlZR1RBVWxwZXhaaEV6NnRoMHN0QlAwT1NDTWhaUXhhU2MyKzlNT0wxVFNpdlc4T01JTjBLNkUKT2xEK1ViWW9qdURWWnRCZDloaVJEOGc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K